Drop unneeded dependency on the `windows` crate & further cleanups (#15)
* Extend `windows` dependency range to `0.58-0.61`

* cargo: Set `rust-version` to keep in sync with the CI MSRV

Set the `rust-version` in `Cargo.toml` for a multitude of reasons
(crates.io shows it to users, and `cargo` can use it in its MSRV-aware
resolver), including the `+nightly -Zminimal-versions generate-lockfile`
step to generate a compatible `version = 3` `Cargo.lock` for MSRV 1.74
to consume, rather than `version = 4` which it doesn't understand yet.

* Fix clippy lints

* Minor code and API cleanups

* Drop unneeded dependency on the `windows` crate

This saves yet one more crate to update, because it was only used to
query the size of the `LUID` type which is always known to be 8 bytes.

If anything the more light-weight `windows_sys` crate should have been
used instead.

* CI: Run on all OS'es

* CI: Diff generated result from `api_gen`

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,12 @@ on:
 jobs:
   rust:
     name: Lint Rust code
-    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        os:
+          - ubuntu-latest
+          - windows-latest
+    runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v4
       - name: Cargo fmt
@@ -17,7 +22,12 @@ jobs:
 
   rust-msrv:
     name: Build-test MSRV (1.74) with minimal crate dependencies
-    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        os:
+          - ubuntu-latest
+          - windows-latest
+    runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v4
       - uses: dtolnay/rust-toolchain@nightly
@@ -26,3 +36,20 @@ jobs:
       - uses: dtolnay/rust-toolchain@1.74.0
       - name: Cargo check
         run: cargo check --workspace --all-targets
+
+  generate:
+    runs-on: windows-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Checkout submodule
+        # Manually update submodules with --checkout because they are configured with update=none and will be skipped otherwise
+        run: git submodule update --recursive --init --force --checkout
+      - name: Run generator
+        run: cargo r -p api_gen
+      - name: Normalize line endings
+        run: |
+          git add --renormalize -u
+          git reset
+      - name: Diff autogen result
+        shell: bash
+        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with cargo run -p api_gen!"; git diff; false)
